# Generated by Django 2.2.2 on 2019-06-19 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_actividad', models.CharField(max_length=30)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('nie', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_alumno', models.CharField(max_length=50)),
                ('apellidos_alumno', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codigo_asignatura', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_asignatura', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('dui', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_encargado', models.CharField(max_length=200)),
                ('direcion', models.CharField(max_length=200)),
                ('parentescto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('codigo_especialidad', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_modulo', models.CharField(max_length=10)),
                ('nombre_modulo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_nivel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_periodo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Promedio',
            fields=[
                ('id_promedio', models.IntegerField(primary_key=True, serialize=False)),
                ('valor_promedio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_secion', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NotasActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Actividad')),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Alumno')),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Asignatura')),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Especialidad')),
                ('id_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Nivel')),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Periodo')),
                ('id_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateField()),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.Alumno')),
                ('especialidad_matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Especialidad')),
                ('nivel_matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Nivel')),
                ('seccion_matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad_Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Asignatura')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Especialidad')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Modulo')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Nivel')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Encargado'),
        ),
    ]
