# Generated by Django 2.2.2 on 2019-06-23 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20190620_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['alumno']},
        ),
    ]
