# Generated by Django 2.2.2 on 2019-06-23 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20190623_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notasactividad',
            options={'ordering': ['-id_alumno']},
        ),
    ]
